build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
  python_packages:
    - "pillow==10.3.0"
    - "accelerate==0.30.1"
    - "torch==2.3.0"
    - "transformers==4.41.0"
    - "sentencepiece==0.1.99"
    - "protobuf==3.19.6"
    - "huggingface-hub==0.25.2"
